#pragma once
#define CONFIG_XIAOZHI_KNX_IP_MAX_OBJECTS 128
#define CONFIG_ESP_KNX_IP_MAX_GROUP_ADDRESSES 128
#define CONFIG_XIAOZHI_KNX_IP_PHYSICAL_ADDRESS "15.15.199"
#define CONFIG_XIAOZHI_KNX_IP_MULTICAST_ADDRESS "224.0.23.12"
#define CONFIG_XIAOZHI_KNX_IP_UDP_PORT 3671
#define CONFIG_XIAOZHI_KNX_IP_RECONNECT_INTERVAL_MS 10000
#define CONFIG_XIAOZHI_KNX_IP_DEBUG 0
